### ISSUE TITLE
(24H2 - latest windows release) error after starting latest release 1.7 in Windows 11

### ISSUE THREAD

**Issue by Comodore125** [bigclownlabs/bch-playground#12]
A JavaScript error occurred in the main process

Uncaught Exception:

Error: listen EACCES: permission denied 0.0.0.0:8000
at Server.setupListenHandle [as _listen2] (node:net:1355:21)
at listenInCluster (node:net:1420:12)
at Server.listen (node:net:1508:7)
at Function.listen (C:\Users\jkm\AppData\Local\Programs\hardwario-playground\resources\app.asar\node_modules\express\lib\application.js:618:24)
at Object.init (C:\Users\jkm\AppData\Local\Programs\hardwario-playground\resources\app.asar\src\server.js:50:9)
at Object.setup (C:\Users\jkm\AppData\Local\Programs\hardwario-playground\resources\app.asar\src\index.js:40:12)
at Object.<anonymous> (C:\Users\jkm\AppData\Local\Programs\hardwario-playground\resources\app.asar\src\main.js:15:3)
at Module._compile (node
/modules/cjs/loader:1120:14)
at Module._extensions..js (node
/modules/cjs/loader:1175:10)
at Module.load (node
/modules/cjs/loader:988:32)

Hopefuly I dont need it fixed now, I am gona be flashing the hardwario device with changes firmware via my raspberry pi where I am running the software. But its good that this will be known. Would be nice if it did not start with error 

Tried  netstat -ano | findstr :8000 - to be sure - but I dont seem to have blocking port. 

I think there is new operating system API that handles firewall, at least since I installed this release I've been getting firewall asking me if I am willing to open connection for specific software that was already allowed in older versions.

**Comment by SmejkalJakub** [comment]
Hello,

can I ask from what version did you upgrade from and also if the old version still works ok?

Thank you

Jakub Smejkal

**Comment by Comodore125** [comment]
I just installed latset release. I updated mainly Win11 itself and I think they changed the way firewalls are handled and I think thats the issue. I am really glad that there were mainly updates to hardwario raspbian as thats the main part :) so thanks for that.  
But for ppl who really rely on this it seems to be broken in latest windows release 24H2. 
I actually did reinstall of windows 11. Will try to download this now and install it and see. I am certain it will get replicated.

**Comment by Comodore125** [comment]
Actually, good news. After doing reinstall of whole WIN11 starting directly from 24H2 this software managed to ask for firewall permission and then I got zero errors. But for those who did not do reinstall and just upgraded windows (from 23H2 to 24H2 or earlier to 24H2) this issue might be totaly relevant. They might just see the error.

**Comment by hubpav** [comment]
@Comodore125 Thank you for the valuable feedback. We are glad this helped. Still, we are wondering what is the technical reason for that. Perhaps @SmejkalJakub will address it as a side effect as soon as he gets the new version with the updated Electron.js (and other NPMs) out.
